
name: main

on:
  push:
    branches: [ "master", "devel" ]
  pull_request:
    branches: [ "master", "devel" ]
  schedule:
    - cron: "0 14 * * 1"

jobs:
  quicktest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y python3 python3-pip

      - name: Run build
        run: pip3 install .[test]

      - name: Run tests and collect coverage
        run: pytest -v -m "not slow" --cov=./src

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  installtest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y python3 python3-pip

      - name: Run build
        run: pip3 install .

      - name: Seek help
        run: python -m kivecli.runkive --help

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y python3 python3-pip

      - name: Run build
        run: pip3 install .[dev]

      - name: Run linter
        run: flake8

  typechecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y python3 python3-pip

      - name: Run build
        run: pip3 install .[dev]

      - name: Run typechecker
        run: mypy

