
name: ci

on:
  push:
    branches: [ "master", "devel" ]
  pull_request:
    branches: [ "master", "devel" ]
  workflow_dispatch:

jobs:
  run-ci:
    uses: ./.github/workflows/ci-reusable.yml
    secrets: inherit

